"use client";
import Link from "next/link";
import { Check, Eye, Pencil, Plus, Search, Send, Trash2, X } from "lucide-react";
import { useMemo, useState } from "react";
import { demoInboundBatches, demoOutboundBatches, demoPosEvents, demoPosMappings } from "../demo-data";
import type { PosInboundBatch, PosMapping, PosOutboundBatch } from "../types";

const date = (value: string) => new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Karachi" }).format(new Date(value));
function Pill({ value }: { value: string }) { const good = ["mapped", "sent", "approved"].includes(value); const bad = ["blocked", "failed", "rejected"].includes(value); return <span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold uppercase ${good ? "bg-emerald-50 text-emerald-700" : bad ? "bg-red-50 text-red-700" : "bg-blue-50 text-blue-700"}`}>{value.replaceAll("_", " ")}</span>; }

export function PosMappingsList() { const [records, setRecords] = useState(demoPosMappings); const [query, setQuery] = useState(""); const filtered = records.filter((item) => `${item.externalDisplayName} ${item.externalEntityKey} ${item.internalEntityId}`.toLowerCase().includes(query.toLowerCase())); return <Panel title="Mappings" description="Connect internal records to provider-facing POS keys." action={<Link href="/pos-integration/mappings/new" className="inline-flex h-10 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-white"><Plus className="size-4" />Add mapping</Link>}><SearchBox value={query} setValue={setQuery} /><div className="overflow-x-auto"><table className="w-full min-w-[950px] text-left text-sm"><Head labels={["Internal record", "External record", "Display name", "Required", "Status", "Actions"]} /><tbody className="divide-y divide-border">{filtered.map((item) => <tr key={item.id}><td className="px-5 py-4 font-semibold">{item.internalEntityType}:{item.internalEntityId}</td><td className="px-5 py-4">{item.externalEntityType}:{item.externalEntityKey}</td><td className="px-5 py-4">{item.externalDisplayName ?? "—"}</td><td className="px-5 py-4">{item.isRequired ? "Yes" : "No"}</td><td className="px-5 py-4"><Pill value={item.status} /></td><td className="px-5 py-4"><div className="flex justify-end gap-2"><IconLink href={`/pos-integration/mappings/${item.id}/edit`}><Pencil className="size-4" /></IconLink><IconButton onClick={() => setRecords((current) => current.filter((record) => record.id !== item.id))}><Trash2 className="size-4" /></IconButton></div></td></tr>)}</tbody></table></div></Panel>; }

export function PosOutboundList() { const [records, setRecords] = useState<PosOutboundBatch[]>(demoOutboundBatches); function create() { setRecords((current) => [{ id: crypto.randomUUID(), status: "pending", itemCount: demoPosMappings.filter((item) => item.status === "mapped").length, sentAt: null, errorMessage: null, createdAt: new Date().toISOString() }, ...current]); } return <><Stats values={[["Eligible mappings", "2"], ["Blocked rows", "1"], ["Readiness", "Ready"]]} /><div className="mt-6"><Panel title="Outbound batches" description="Bundle mapped records and mark approved batches as sent." action={<button onClick={create} className="inline-flex h-10 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-white"><Plus className="size-4" />Create batch</button>}><BatchTable records={records} route="outbound" action={(batch) => batch.status === "pending" ? <IconButton onClick={() => setRecords((current) => current.map((item) => item.id === batch.id ? { ...item, status: "sent", sentAt: new Date().toISOString() } : item))}><Send className="size-4" /></IconButton> : null} /></Panel></div></>; }

export function PosInboundList() { const [records, setRecords] = useState<PosInboundBatch[]>(demoInboundBatches); function review(id: string, status: "approved" | "rejected") { setRecords((current) => current.map((item) => item.id === id ? { ...item, status, reviewedBy: "Owner Admin", reviewedAt: new Date().toISOString() } : item)); } return <Panel title="Inbound batches" description="Review data received from the POS before accepting it."><BatchTable records={records} route="inbound" action={(batch) => batch.status === "pending_review" ? <><IconButton onClick={() => review(batch.id, "approved")}><Check className="size-4" /></IconButton><IconButton onClick={() => review(batch.id, "rejected")}><X className="size-4" /></IconButton></> : null} /></Panel>; }

export function PosEventsList() { const [query, setQuery] = useState(""); const filtered = useMemo(() => demoPosEvents.filter((item) => `${item.eventType} ${item.description} ${item.performedBy}`.toLowerCase().includes(query.toLowerCase())), [query]); return <><Stats values={[["Total events", String(demoPosEvents.length)], ["Connection events", "1"], ["Batch events", "1"]]} /><div className="mt-6"><Panel title="Events" description="Newest connection, mapping and batch events."><SearchBox value={query} setValue={setQuery} /><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><Head labels={["Event", "Description", "Performed by", "Created"]} /><tbody className="divide-y divide-border">{filtered.map((item) => <tr key={item.id}><td className="px-5 py-4 font-semibold">{item.eventType.replaceAll("_", " ")}</td><td className="px-5 py-4">{item.description ?? "—"}</td><td className="px-5 py-4">{item.performedBy ?? "System"}</td><td className="px-5 py-4">{date(item.createdAt)}</td></tr>)}</tbody></table></div></Panel></div></>; }

function BatchTable<T extends PosOutboundBatch | PosInboundBatch>({ records, route, action }: { records: T[]; route: string; action: (batch: T) => React.ReactNode }) { return <div className="overflow-x-auto"><table className="w-full min-w-[750px] text-left text-sm"><Head labels={["Batch ID", "Items", "Created", "Status", "Actions"]} /><tbody className="divide-y divide-border">{records.map((batch) => <tr key={batch.id}><td className="px-5 py-4 font-semibold">{batch.id.slice(0, 8)}</td><td className="px-5 py-4">{batch.itemCount}</td><td className="px-5 py-4">{date(batch.createdAt)}</td><td className="px-5 py-4"><Pill value={batch.status} /></td><td className="px-5 py-4"><div className="flex justify-end gap-2"><IconLink href={`/pos-integration/${route}/${batch.id}`}><Eye className="size-4" /></IconLink>{action(batch)}</div></td></tr>)}</tbody></table></div>; }
function Panel({ title, description, action, children }: { title: string; description: string; action?: React.ReactNode; children: React.ReactNode }) { return <section className="overflow-hidden rounded-2xl border border-border bg-white"><div className="flex items-center justify-between gap-4 border-b border-border p-5"><div><h2 className="font-bold">{title}</h2><p className="mt-1 text-xs text-muted">{description}</p></div>{action}</div>{children}</section>; }
function Stats({ values }: { values: string[][] }) { return <div className="grid gap-4 sm:grid-cols-3">{values.map(([label, value]) => <article key={label} className="rounded-2xl border border-border bg-white p-5"><p className="text-xs text-muted">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></article>)}</div>; }
function SearchBox({ value, setValue }: { value: string; setValue: (value: string) => void }) { return <label className="relative m-4 block"><Search className="absolute left-4 top-1/2 size-4 -translate-y-1/2 text-muted" /><input value={value} onChange={(event) => setValue(event.target.value)} placeholder="Search..." className="h-11 w-full rounded-xl border border-border pl-11 pr-4 text-sm" /></label>; }
function Head({ labels }: { labels: string[] }) { return <thead className="bg-surface-secondary text-xs uppercase text-muted"><tr>{labels.map((label) => <th key={label} className={`px-5 py-4 ${label === "Actions" ? "text-right" : ""}`}>{label}</th>)}</tr></thead>; }
function IconLink({ href, children }: { href: string; children: React.ReactNode }) { return <Link href={href} className="flex size-9 items-center justify-center rounded-xl border border-border">{children}</Link>; }
function IconButton({ onClick, children }: { onClick: () => void; children: React.ReactNode }) { return <button type="button" onClick={onClick} className="flex size-9 items-center justify-center rounded-xl border border-border">{children}</button>; }
