import { expenseSchema } from "./schemas";
import type { CrudResourceConfig } from "@/types/crud-resource";
export const expenseConfig: CrudResourceConfig = {
  title: "Operations Expenses",
  singular: "expense",
  description: "Record operating expenses and payment information.",
  route: "/operations/expenses",
  endpoint: "/operations/expenses",
  statuses: ["Recorded", "Approved", "Cancelled"],
  searchKeys: ["category", "description", "payment_method", "status"],
  schema: expenseSchema,
  fields: [
    {
      key: "category",
      label: "Category",
      type: "text",
      required: true,
      table: true,
    },
    {
      key: "description",
      label: "Description",
      type: "textarea",
      required: false,
      table: true,
    },
    {
      key: "amount",
      label: "Amount",
      type: "number",
      required: true,
      table: true,
      currency: true,
    },
    {
      key: "location_id",
      label: "Location",
      type: "select",
      required: false,
      table: false,
      options: ["b3f1c2e0-1234-4a5b-9c6d-7e8f9a0b1c2d"],
    },
    {
      key: "expense_date",
      label: "Expense date",
      type: "datetime-local",
      required: true,
      table: true,
    },
    {
      key: "payment_method",
      label: "Payment method",
      type: "select",
      required: false,
      table: true,
      options: ["cash", "card", "bank_transfer"],
    },
    {
      key: "status",
      label: "Status",
      type: "select",
      required: true,
      table: true,
      options: ["Recorded", "Approved", "Cancelled"],
    },
  ],
  records: [
    {
      id: 1,
      category: "Utilities",
      description: "Electricity bill - August",
      amount: 12500,
      location_id: "b3f1c2e0-1234-4a5b-9c6d-7e8f9a0b1c2d",
      expense_date: "2026-08-26T12:00:00.000Z",
      payment_method: "bank_transfer",
      status: "Recorded",
      created_at: "2026-08-27T10:00:00.000Z",
      updated_at: "2026-08-27T10:00:00.000Z",
      deleted_at: null,
    },
    {
      id: 2,
      category: "Cleaning",
      description: "Cleaning supplies",
      amount: 3500,
      location_id: "b3f1c2e0-1234-4a5b-9c6d-7e8f9a0b1c2d",
      expense_date: "2026-08-27T10:00:00.000Z",
      payment_method: "cash",
      status: "Approved",
      created_at: "2026-08-27T10:00:00.000Z",
      updated_at: "2026-08-27T10:00:00.000Z",
      deleted_at: null,
    },
  ],
};
export function findDemoExpense(id: number) {
  return expenseConfig.records.find((item) => item.id === id);
}
