export {
  createOnboardingLocation,
  disableMfa,
  forgotPassword,
  getCurrentUser,
  getMyLocations,
  loginUser,
  logoutUser,
  registerUser,
  resendOtp,
  resetPassword,
  setActiveLocation,
  setupMfa,
  verifyMfa,
  verifyEmail,
} from "./auth.api";
